### ISSUE TITLE
Creating AWS Lambda Layer leads to ._snappy_cfi missing problem

### ISSUE THREAD

**Issue by dgrahn** [andrix/python-snappy#82]
I'm creating an AWS Lambda layer for snappy. Here is my code.

    docker run --rm -v $(pwd):/foo -w /foo lambci/lambda:build-python3.7 \
        /bin/bash -c "yum install -y snappy-devel; pip install python-snappy -t pkg/python
    mv pkg/python/snappy/_snappy.cpython-37m-x86_64-linux-gnu.so \
        pkg/python/snappy/_snappy_cffi.cpython-37m-x86_64-linux-gnu.so

The second line is necessary, otherwise I run into issues with the missing `._snappy_cffi module.  I'm thinking this is a bug, but I'm not sure what the solution is. This is just a workaround.

**Comment by dgrahn** [comment]
Actually. It appears that this issue resolved without moving the module as long as libsnappy.so* is present.

**Comment by stevesuh** [comment]
@dgrahn I'm doing something very similar but I'm still getting the error: `No module named 'snappy._snappy_cffi'`.

```
export PKG_DIR="python/lib/python3.6/site-packages"
yum --assumeyes install snappy-devel
 mkdir -p ${PKG_DIR}
pip install -r requirements.txt -t ${PKG_DIR}
```

When I ssh into the docker I see this:
```
bash-4.2# echo $LD_LIBRARY_PATH
/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
bash-4.2# find . -name *snapp*.so
./root/revelation-services/modules/get_kcf_waveform_data/build_layer/python/lib/python3.6/site-packages/snappy/_snappy.cpython-36m-x86_64-linux-gnu.so
./usr/lib64/libsnappy.so
```

Only difference is that we are using python3.6 image.
```
 docker:
      - image: lambci/lambda:build-python3.6
```

**Comment by pprados** [comment]
Step 1: Download libsnappy.so.1 from lambda image.
In Makefile:
```
PYTHON_VERSION=3.7
libsnappy-$(PYTHON_VERSION).so:
	@echo -e "$(green)Download lambda version of libsnappy-$(PYTHON_VERSION).so...$(normal)"
	docker run --rm -v $$(pwd):/foo -w /foo lambci/lambda:build-python$(PYTHON_VERSION) \
	/bin/bash -c "yum install -y snappy-devel ; cp /usr/lib64/libsnappy.so.1 /foo/libsnappy-$(PYTHON_VERSION).so"
	sudo chown $(USER):$(USER) libsnappy-$(PYTHON_VERSION).so
	chmod 600 libsnappy-$(PYTHON_VERSION).so
```

Step 2: build layer with the Makefile
```
build-ParquetLayer: layers/parquet/requirements.txt template.yaml Makefile libsnappy-$(PYTHON_VERSION).so
	# executed inside `sam build`
	umask 0
	mkdir -p "$(ARTIFACTS_DIR)/python"
	python -m pip install -r layers/parquet/requirements.txt -t "$(ARTIFACTS_DIR)/python"
	mkdir -p "$(ARTIFACTS_DIR)/lib"
	cp libsnappy-$(PYTHON_VERSION).so "$(ARTIFACTS_DIR)/lib/libsnappy.so.1"
```

Step 3: declare Lambda layer in template.yaml
```
  ParquetLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - python3.7
        - python3.8
      Description: Parquet loader layers
      LayerName: parquet
      LicenseInfo: BSD 2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
```

Step 4: use the layer
```
    Layers:
      - !Ref ParquetLayer
```
